// 星辰论坛项目/CSDN-f/src/pages/login.vue
<template>
  <div class="login">
    <!-- 粒子背景 canvas，个人特色 -->
    <canvas ref="particleCanvas" class="particles-canvas"></canvas>

    <div class="form">
      <h2>星辰论坛</h2>
      <input type="text" placeholder="用户名" v-model="user.name" />
      <input type="password" placeholder="密码" v-model="user.password" />
      <div class="buttons">
        <el-button @click="handleRegister">前去注册</el-button>
        <el-button @click="Login">登录</el-button>
      </div>
      <br />
      <footer class="footer" @click="show">StellarNet Studio</footer>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import type { User } from '../api/user'
import { getLogin } from '../api/login'

const particleCanvas = ref<HTMLCanvasElement | null>(null)

// 粒子配置项
const config = {
  number: 100,
  color: '#000000',
  opacity: 0.5,
  size: 2,
  lineColor: '#000000',
  lineOpacity: 0.3,
  lineWidth: 1,
  linkDistance: 150,
  velocity: 1.5,
}

interface Particle {
  x: number
  y: number
  vx: number
  vy: number
}

const particles: Particle[] = []

function initParticles() {
  const canvas = particleCanvas.value
  if (!canvas) return

  const ctx = canvas.getContext('2d')
  if (!ctx) return

  // 设置 canvas 大小
  function resize() {
    if (!canvas) return
    canvas.width = window.innerWidth
    canvas.height = window.innerHeight
  }

  window.addEventListener('resize', resize)
  resize()

  // 初始化粒子
  for (let i = 0; i < config.number; i++) {
    particles.push({
      x: Math.random() * canvas.width,
      y: Math.random() * canvas.height,
      vx: (Math.random() - 0.5) * config.velocity,
      vy: (Math.random() - 0.5) * config.velocity,
    })
  }

  // 绘制粒子
  function draw() {
    if (!ctx || !canvas) return

    ctx.clearRect(0, 0, canvas.width, canvas.height)
    ctx.fillStyle = config.color
    ctx.globalAlpha = config.opacity

    for (const p of particles) {
      ctx.beginPath()
      ctx.arc(p.x, p.y, config.size, 0, Math.PI * 2)
      ctx.fill()

      // 更新位置
      p.x += p.vx
      p.y += p.vy

      if (p.x <= 0 || p.x >= canvas.width) p.vx *= -1
      if (p.y <= 0 || p.y >= canvas.height) p.vy *= -1
    }

    // 连线
    for (let i = 0; i < particles.length; i++) {
      for (let j = i + 1; j < particles.length; j++) {
        const dx = particles[i].x - particles[j].x
        const dy = particles[i].y - particles[j].y
        const dist = Math.sqrt(dx * dx + dy * dy)

        if (dist < config.linkDistance) {
          ctx.strokeStyle = config.lineColor
          ctx.globalAlpha = config.lineOpacity
          ctx.beginPath()
          ctx.moveTo(particles[i].x, particles[i].y)
          ctx.lineTo(particles[j].x, particles[j].y)
          ctx.stroke()
        }
      }
    }

    requestAnimationFrame(draw)
  }

  draw()
}
const router = useRouter()
function show() {
  router.push('/our')
}
const user = ref<User>({
  id: '1',
  name: '',
  password: '',
  pic: '',
})
async function Login() {
  try {
    const userInfo = await getLogin(user.value.name, user.value.password)
    if (userInfo) {
      console.log('登录成功:', userInfo)
      localStorage.setItem('username', userInfo.name)
      localStorage.setItem('userid', userInfo.id)
      localStorage.setItem('userpic', userInfo.pic)
      router.push('/main')
    } else {
      alert('用户名或密码错误')
    }
  } catch (error) {
    console.error('登录失败:', error)
  }
}
function handleRegister() {
  alert('注册按钮被点击')
}

onMounted(() => {
  initParticles()
})
</script>

<style lang="scss" scoped>
.login {
  width: 100vw;
  height: 100vh;
  position: relative;
  overflow: hidden;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #f6f6f6;
}

.particles-canvas {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 0;
}

.form {
  position: relative;
  z-index: 2;
  background: rgba(83, 83, 83, 0.6);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  padding: 40px;
  border-radius: 16px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
  text-align: center;
  color: #fff;
  width: 320px;
  position: relative;

  h2 {
    margin-bottom: 20px;
  }

  input {
    display: block;
    width: 100%;
    padding: 10px;
    margin: 10px 0;
    border: none;
    border-radius: 8px;
    outline: none;
    background: rgba(255, 255, 255, 0.2);
    color: white;
  }
  .buttons {
    display: flex;
    justify-content: space-between;
    button {
      width: 45%;
      padding: 10px;
      background: rgba(255, 255, 255, 0.3);
      color: white;
      border: none;
      border-radius: 8px;
      cursor: pointer;
      transition: background 0.3s ease;
    }
  }

  button:hover {
    background: rgba(255, 255, 255, 0.5);
  }
  .footer {
    position: absolute;
    bottom: 10px;
    left: 50%;
    transform: translateX(-50%);
    color: #919191;
    cursor: pointer;
    &:hover {
      color: #fff;
    }
  }
}
@media (max-width: 768px) {
  .form {
    width: 80%;
  }
}
</style>

// 星辰企业综合管理系统/xingchen_manage_f/src/view/Login/login.tsx

import { useRef, useEffect, useState } from 'react';
import './index.scss';
import { useNavigate } from 'react-router-dom';
import { Button, Input, Form, message } from 'antd';
import { UserOutlined, LockOutlined } from '@ant-design/icons';

function Login() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const navigate = useNavigate();
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);

  const config = {
    number: 80,
    color: '#04c8c4',
    opacity: 0.6,
    size: 2,
    lineColor: '#9fff',
    lineOpacity: 0.3,
    lineWidth: 1,
    linkDistance: 150,
    velocity: 1.0,
  };

  const particles: Array<{
    x: number;
    y: number;
    vx: number;
    vy: number;
  }> = [];

  const initParticles = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const resize = () => {
      const mainElement = document.querySelector('.main');
      if (mainElement && canvas) {
        canvas.width = mainElement.clientWidth;
        canvas.height = mainElement.clientHeight;
      }
    };

    const initializeParticles = () => {
      const mainElement = document.querySelector('.main');
      if (!mainElement) return;
      const width = mainElement.clientWidth;
      const height = mainElement.clientHeight;

      for (let i = 0; i < config.number; i++) {
        particles.push({
          x: Math.random() * width,
          y: Math.random() * height,
          vx: (Math.random() - 0.5) * config.velocity,
          vy: (Math.random() - 0.5) * config.velocity,
        });
      }
    };

    const draw = () => {
      if (!ctx || !canvas) return;

      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.fillStyle = config.color;
      ctx.globalAlpha = config.opacity;

      for (const p of particles) {
        ctx.beginPath();
        ctx.arc(p.x, p.y, config.size, 0, Math.PI * 2);
        ctx.fill();

        p.x += p.vx;
        p.y += p.vy;

        if (p.x <= 0 || p.x >= canvas.width) p.vx *= -1;
        if (p.y <= 0 || p.y >= canvas.height) p.vy *= -1;
      }

      for (let i = 0; i < particles.length; i++) {
        for (let j = i + 1; j < particles.length; j++) {
          const dx = particles[i].x - particles[j].x;
          const dy = particles[i].y - particles[j].y;
          const dist = Math.sqrt(dx * dx + dy * dy);

          if (dist < config.linkDistance) {
            ctx.strokeStyle = config.lineColor;
            ctx.globalAlpha = config.lineOpacity;
            ctx.beginPath();
            ctx.moveTo(particles[i].x, particles[i].y);
            ctx.lineTo(particles[j].x, particles[j].y);
            ctx.stroke();
          }
        }
      }

      requestAnimationFrame(draw);
    };

    window.addEventListener('resize', resize);
    resize();
    initializeParticles();
    draw();

    return () => {
      window.removeEventListener('resize', resize);
    };
  };

  useEffect(() => {
    const cleanup = initParticles();
    return () => {
      if (cleanup && typeof cleanup === 'function') {
        cleanup();
      }
    };
  }, []);

  const handleLogin = async () => {
    setLoading(true);
    try {
      // 模拟登录请求
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      // 登录成功
      message.success('登录成功！');
      navigate('/main');
    } catch (error) {
      message.error('登录失败，请检查用户名和密码');
    } finally {
      setLoading(false);
    }
  };

  const handleShow = () => {
    navigate('/our');
  };

  return (
    <div className="login">
      <div className="pic">
        <img src="/1687678759422461.png" alt="Background" className="i"/>
      </div>
      <div className="main">
        <canvas ref={canvasRef} className="particles-canvas"/>
        <div className='form'>
            <div className='title1'>欢迎使用</div>
            <div className='title2'>---星辰管理系统</div>
            <Form 
              form={form} 
              layout="vertical" 
              onFinish={handleLogin}
              requiredMark={false}
            >
              <Form.Item
                name="username"
                rules={[{ required: true, message: '请输入用户名!' }]}
              >
                <Input 
                  size="large" 
                  placeholder="用户名" 
                  prefix={<UserOutlined />}
                />
              </Form.Item>

              <Form.Item
                name="password"
                rules={[{ required: true, message: '请输入密码!' }]}
              >
                <Input.Password 
                  size="large" 
                  placeholder="密码" 
                  prefix={<LockOutlined />}
                />
              </Form.Item>

              <div className='btn'>
                <Button 
                  className='reg' 
                  size="large"
                  onClick={() => message.info('注册功能暂未开放')}
                >
                  注册
                </Button>
                <Button 
                  type="primary" 
                  htmlType="submit" 
                  className='enter' 
                  size="large"
                  loading={loading}
                >
                  登录
                </Button>
              </div>
            </Form>
        </div>
        <div className="footer" onClick={handleShow}>
          StellarNet Studio
        </div>
      </div>
    </div>
  );
}

export default Login;
